const ORDER_TUPLE = {
  type: "tuple",
  components: [
    { name: "amount", type: "uint256" },
    { name: "fiatAmount", type: "uint256" },
    { name: "placedTimestamp", type: "uint256" },
    { name: "completedTimestamp", type: "uint256" },
    { name: "userCompletedTimestamp", type: "uint256" },
    { name: "acceptedMerchant", type: "address" },
    { name: "user", type: "address" },
    { name: "recipientAddr", type: "address" },
    { name: "pubkey", type: "string" },
    { name: "encUpi", type: "string" },
    { name: "userCompleted", type: "bool" },
    { name: "status", type: "uint8" },
    { name: "orderType", type: "uint8" },
    {
      name: "disputeInfo",
      type: "tuple",
      components: [
        { name: "raisedBy", type: "uint8" },
        { name: "status", type: "uint8" },
        { name: "redactTransId", type: "uint256" },
        { name: "accountNumber", type: "uint256" },
      ],
    },
    { name: "id", type: "uint256" },
    { name: "userPubKey", type: "string" },
    { name: "encMerchantUpi", type: "string" },
    { name: "acceptedAccountNo", type: "uint256" },
    { name: "assignedAccountNos", type: "uint256[]" },
    { name: "currency", type: "bytes32" },
    { name: "preferredPaymentChannelConfigId", type: "uint256" },
    { name: "circleId", type: "uint256" },
  ],
} as const;

export const DIAMOND_ABI = [
  {
    type: "function",
    name: "acceptOrder",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_orderId", type: "uint256" },
      { name: "_userEncUpi", type: "string" },
      { name: "_pubKey", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "completeOrder",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_orderId", type: "uint256" },
      { name: "merchantUpi", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "fetchMerchantAssignedOrders",
    stateMutability: "view",
    inputs: [{ name: "_merchant", type: "address" }],
    outputs: [{ ...ORDER_TUPLE, name: "", type: "tuple[]" }],
  },
  {
    type: "function",
    name: "fetchMerchantAcceptedOrders",
    stateMutability: "view",
    inputs: [{ name: "_merchant", type: "address" }],
    outputs: [{ ...ORDER_TUPLE, name: "", type: "tuple[]" }],
  },
  {
    type: "function",
    name: "getOrdersById",
    stateMutability: "view",
    inputs: [{ name: "orderId", type: "uint256" }],
    outputs: [{ ...ORDER_TUPLE, name: "" }],
  },
  {
    type: "function",
    name: "register",
    stateMutability: "nonpayable",
    inputs: [
      { name: "circleId", type: "uint256" },
      { name: "stakeAmount", type: "uint256" },
      { name: "telegramId", type: "string" },
      { name: "currency", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addMerchantPaymentChannel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "paymentChannelConfigId", type: "uint256" },
      { name: "accountNo", type: "uint256" },
      { name: "label", type: "string" },
      { name: "isMonthlyVolumeUnlimited", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "updateFiatAmount",
    stateMutability: "nonpayable",
    inputs: [
      { name: "merchant", type: "address" },
      { name: "accountNo", type: "uint256" },
      { name: "amountDelta", type: "int256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "createCircle",
    stateMutability: "nonpayable",
    inputs: [
      { name: "currency", type: "bytes32" },
      { name: "admin", type: "address" },
      { name: "name", type: "string" },
      { name: "communityUrl", type: "string" },
      { name: "adminCommunityUrl", type: "string" },
      { name: "autoApprovePaymentChannels", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getMerchantDetails",
    stateMutability: "view",
    inputs: [{ name: "_merchant", type: "address" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "stake", type: "uint256" },
          { name: "isOnline", type: "bool" },
          { name: "totalVolume", type: "uint256" },
          { name: "withdrawnAmount", type: "uint256" },
          { name: "lastVolumeResetTimestamp", type: "uint256" },
          { name: "accruedFees", type: "uint256" },
          { name: "isRegistered", type: "bool" },
          { name: "currency", type: "bytes32" },
          { name: "freeAmountUsdc", type: "uint256" },
          { name: "circleId", type: "uint256" },
          { name: "delegatedStake", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "isCurrencySupported",
    stateMutability: "view",
    inputs: [{ name: "currency", type: "bytes32" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getCurrentPaymentChannelId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "launchCurrency",
    stateMutability: "nonpayable",
    inputs: [
      { name: "currency", type: "bytes32" },
      {
        name: "priceConfig",
        type: "tuple",
        components: [
          { name: "buyPrice", type: "uint256" },
          { name: "sellPrice", type: "uint256" },
          { name: "buyPriceOffset", type: "int256" },
          { name: "baseSpread", type: "uint256" },
        ],
      },
      { name: "priceBumpPercentage", type: "int256" },
      { name: "priceUpdater", type: "address" },
      { name: "minStake", type: "uint256" },
      { name: "monthlyVolumeLimit", type: "uint256" },
      { name: "merchantFeePercentage", type: "uint256" },
      { name: "monthlyBuyOrderLimit", type: "uint256" },
      { name: "userYearlyVolumeLimit", type: "uint256" },
      { name: "rpPerUsdtLimitNumerator", type: "uint256" },
      { name: "rpPerUsdtLimitDenominator", type: "uint256" },
      { name: "maxBuyTxLimit", type: "uint256" },
      { name: "maxSellTxLimit", type: "uint256" },
      { name: "assignMerchantsCount", type: "uint256" },
      { name: "smallOrderThreshold", type: "uint256" },
      { name: "smallOrderFixedFee", type: "uint256" },
      { name: "maxFiatThresholdPercentage", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setStakeConfig",
    stateMutability: "nonpayable",
    inputs: [
      { name: "currency", type: "bytes32" },
      {
        name: "cfg",
        type: "tuple",
        components: [
          { name: "minCircleAdminP2PStake", type: "uint256" },
          { name: "minMerchantUSDCStake", type: "uint256" },
          { name: "maxMerchantUSDCStake", type: "uint256" },
          { name: "maxMerchantsPerCircle", type: "uint256" },
          { name: "circleStakeToDelegationNumerator", type: "uint256" },
          { name: "circleStakeToDelegationDenominator", type: "uint256" },
          { name: "merchantSelfStakeDelegationNumerator", type: "uint256" },
          { name: "merchantSelfStakeDelegationDenominator", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "getStakeConfig",
    stateMutability: "view",
    inputs: [{ name: "currency", type: "bytes32" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "minCircleAdminP2PStake", type: "uint256" },
          { name: "minMerchantUSDCStake", type: "uint256" },
          { name: "maxMerchantUSDCStake", type: "uint256" },
          { name: "maxMerchantsPerCircle", type: "uint256" },
          { name: "circleStakeToDelegationNumerator", type: "uint256" },
          { name: "circleStakeToDelegationDenominator", type: "uint256" },
          { name: "merchantSelfStakeDelegationNumerator", type: "uint256" },
          { name: "merchantSelfStakeDelegationDenominator", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "addOrUpdatePaymentChannelConfig",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "cfg",
        type: "tuple",
        components: [
          { name: "paymentChannelId", type: "uint256" },
          { name: "name", type: "string" },
          { name: "dailyVolumeLimit", type: "uint256" },
          { name: "currency", type: "bytes32" },
          { name: "isActive", type: "bool" },
        ],
      },
    ],
    outputs: [],
  },
] as const;

export const ERC20_ABI = [
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
] as const;

export enum OrderStatus {
  PLACED = 0,
  ACCEPTED = 1,
  PAID = 2,
  COMPLETED = 3,
  CANCELLED = 4,
}

export enum OrderType {
  BUY = 0,
  SELL = 1,
  PAY = 2,
}
